[package]
name = "rustdoc-index"
version = "0.1.0"
authors = ["octaltree <octaltree@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.24"
string_cache = "0.8.1"
serde = { version = "1.0.125", features = ["derive"] }
serde_json = "1.0.64"
rayon = "1.5.0"
unescape = "0.1.0"
tokio = { version = "1.4.0", features = ["io-util", "macros", "rt-multi-thread"] }
serde_repr = "0.1.6"
#timey = "0.2.0"

[[bin]]
name = "cargo-doc-index"
path = "src/main.rs"
